#!/bin/bash
#
# Check if Keycloak is properly configured for HiveMatrix
#

# Get the directory where this script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$(dirname "$SCRIPT_DIR")"

echo ""
echo "================================================================"
echo "  Keycloak Configuration Checker"
echo "================================================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "This script will help you verify your Keycloak setup."
echo ""
echo "To set up Keycloak for HiveMatrix:"
echo ""
echo "1. Visit the Keycloak Admin Console:"
echo -e "   ${BLUE}http://localhost:8080${NC}"
echo ""
echo "2. Login with:"
echo "   Username: admin"
echo "   Password: admin"
echo ""
echo "3. In the top-left dropdown, check if 'hivematrix' realm exists"
echo ""
echo "4. If it doesn't exist, create it:"
echo "   - Click the dropdown"
echo "   - Click 'Create Realm'"
echo "   - Realm name: hivematrix"
echo "   - Click 'Create'"
echo ""
echo "5. Create the core-client:"
echo "   - Go to Clients → Create client"
echo "   - Client ID: core-client"
echo "   - Name: HiveMatrix Core Service"
echo "   - Click Next"
echo "   - Enable 'Standard flow'"
echo "   - Toggle 'Client authentication' to ON"
echo "   - Click Next"
echo "   - Valid redirect URIs: http://127.0.0.1:5000/auth"
echo "   - Click Save"
echo ""
echo "6. Get the client secret:"
echo "   - Go to Clients → core-client → Credentials tab"
echo "   - Copy the 'Client secret'"
echo "   - Add it to $PARENT_DIR/hivematrix-core/.flaskenv"
echo "     KEYCLOAK_CLIENT_SECRET='<your-secret-here>'"
echo ""
echo "7. Create a test user:"
echo "   - Go to Users → Create new user"
echo "   - Username: (your choice, e.g., 'dhamner')"
echo "   - Email: (optional)"
echo "   - Click Create"
echo "   - Go to Credentials tab"
echo "   - Set password"
echo "   - Toggle 'Temporary' to OFF"
echo "   - Click 'Set password'"
echo ""
echo "8. Create the admins group and add mapper:"
echo "   - Go to Groups → Create group"
echo "   - Name: admins"
echo "   - Click Create"
echo "   - Go to Users → (your user) → Groups tab"
echo "   - Select 'admins' and click 'Join'"
echo "   - Go to Clients → core-client → Client scopes"
echo "   - Click on 'core-client-dedicated'"
echo "   - Click 'Add mapper' → 'By configuration' → 'Group Membership'"
echo "   - Name: groups"
echo "   - Token Claim Name: groups"
echo "   - Full group path: OFF"
echo "   - Add to userinfo: ON"
echo "   - Click Save"
echo ""
echo "9. Restart Core service:"
echo "   cd $SCRIPT_DIR"
echo "   python cli.py restart core"
echo ""
echo "10. Try logging in at:"
echo -e "    ${GREEN}http://localhost:8000${NC}"
echo ""
echo "================================================================"
echo ""
